<?php

    require_once(__DIR__."/../interface/IHasSettings.php");
    require_once(__DIR__."/../interface/ISettings.php");

    abstract class AbstractHasSettings implements IHasSettings {

        /**
         * An abstract class for classes that have settings
         * 
         * @var ISettings $settings settings
         */

        private ISettings $settings;

        /**
         * Initialize settings - assign the settings object generated by the
         * abstract method generateSettingsObject()
         * 
         * @return void
         */
        protected function initSettings(){
            $this->settings = $this->generateSettingsObject();
        }

        /**
         * Set settings and validate required fields
         * 
         * @param array $settings settings
         * 
         * @return void
         */
        public function setSettings(array $settings){
            $this->settings->set($settings);
            $this->settings->validateRequired();
        }

        /**
         * Get settings
         * 
         * @return array settings
         */
        public function getSettings(){
            return $this->settings->get();;
        }

        /**
         * Must be implemented and must return an ISettings object
         * that this class will use
         * 
         * @return ISettings ISettings object to be used by this class
         */
        abstract protected function generateSettingsObject();
    }